#! /usr/bin/env python3
import re
import sys
import argparse
import uuid
import malaria_profiler as malp
import os
import pathogenprofiler as pp
from uuid import uuid4
import json
import glob
import atexit

__softwarename__ = "malaria_profiler"

conf = None
@atexit.register
def cleanup():
    if "last_traceback" in vars(sys):
        if not args.no_cleanup:
            sys.stderr.write("Cleaning up after failed run\n")
            for f in glob.glob(args.files_prefix+"*"):
                os.remove(f)
        import traceback
        
        if "prefix" in vars(args):
            outfile = "%s.errlog.txt" % args.prefix
        elif "vcf" in vars(args):
            outfile = "%s.errlog.txt" % args.vcf.split("/")[-1]
        elif "outfile" in vars(args):
            outfile = "%s.errlog.txt" % args.outfile
        else:
            outfile = "%s.errlog.txt" % uuid4()
        with open(outfile, "w") as O:
            O.write(f"# {args.software_name} error report\n\n")
            O.write("* OS: %s\n" % sys.platform)
            O.write("* Program version: %s\n" % malp.__version__)
            O.write("* Program version: %s\n" % pp.__version__)
            O.write("* Database version: %s\n" % json.load(open(conf["version"]))["commit"]) if conf else ""
            O.write("* Program call:\n")
            O.write("```\n")
            O.write("%s\n" % vars(args))
            O.write("```\n")

            O.write("## Traceback:\n")
            O.write("```\n")
            traceback.print_tb(sys.last_traceback,file=O)
            O.write("```\n")

            O.write("## Value:\n")
            O.write("```\n")
            O.write("%s" % sys.last_value)
            O.write("```\n")
        pp.errlog("""\n
################################# ERROR #######################################

This run has failed. Please check all arguments and make sure all input files
exist. If no solution is found, please open up an issue at
https://github.com/jodyphelan/Malaria-Profiler/issues/new and paste or attach the
contents of the error log (%s)

###############################################################################
""" % (outfile))



def main_profile(args):

    ### Create folders for results if they don't exist ###
    if pp.nofolder(args.dir):
        os.mkdir(args.dir)

    ### Setup prefix for files ###

    json_output = args.dir+"/"+args.prefix+".results.json"
    text_output = args.dir+"/"+args.prefix+".results.txt"
    csv_output = args.dir+"/"+args.prefix+".results.csv"
    pdf_output = args.dir+"/"+args.prefix+".results.pdf"
    extra_columns = [x.lower() for x in args.add_columns.split(",")] if args.add_columns else []

    if args.external_species_db:
        species_db = pp.get_species_db(args.software_name,args.external_species_db)
    else:
        species_db = pp.get_species_db(args.software_name,args.species_db)

    
    if not args.no_species:
        species_prediction = malp.speciate(args)
    else:
        species_prediction = {}


    results = {"id":args.prefix,"species": species_prediction}
    results['software_version'] = malp.__version__
    results['pipeline_software'] = [{"Analysis":"Kmer counting","Program":"kmc"}]
    results['species_db_version'] = json.load(open(species_db["version"]))

    if not args.external_resistance_db and not args.resistance_db:
        if len(species_prediction)==1:
            sys.stderr.write("No resistance database was specified. Attempting to use database based on species prediction...\n")
            db_name = species_prediction[0]["species"].replace(" ","_")
            conf = pp.get_resistance_db(args.software_name,db_name,fcheck=False)
        if len(species_prediction)>1 or len(species_prediction)==0 or not os.path.isfile(conf["ref"]):
            if len(species_prediction)>1:
                sys.stderr.write(f"Multiple species found.\n")
            elif len(species_prediction)==0:
                sys.stderr.write(f"Species classification failed.\n")
            elif not os.path.isfile(conf["ref"]):
                sys.stderr.write(f"No resistance db found for {db_name}.\n")
            
            conf = None

            json.dump(results,open(json_output,"w"))
            if args.txt:
                malp.write_text(results,conf,text_output,extra_columns,reporting_af=args.reporting_af,sep="\t")
            if args.csv:
                malp.write_text(results,conf,text_output,extra_columns,reporting_af=args.reporting_af,sep=",")

            sys.stderr.write("Profiling complete!\n")
            quit(0)
        conf = pp.get_resistance_db(args.software_name,db_name)
    elif args.external_resistance_db:
        conf = pp.get_resistance_db(args.software_name,args.external_resistance_db)
    elif args.resistance_db:
        conf = pp.get_resistance_db(args.software_name,args.resistance_db)




    ### Set up platform dependant parameters ###
    if args.platform=="nanopore":
        args.mapper = "minimap2"
        if args.caller=="gatk":
            args.caller = "freebayes"
        args.no_trim=True
        run_delly = False
    else:
        if args.no_delly:
            run_delly = False
        else:
            run_delly = True

    

    ### Create bam file if fastq has been supplied ###
    if args.bam==None:
        if args.read1 and args.read2 and args.no_trim:
            # Paired + no trimming
            fastq_obj = pp.fastq(args.read1,args.read2)
        elif args.read1 and args.read2 and not args.no_trim:
            # Paired + trimming
            untrimmed_fastq_obj = pp.fastq(args.read1,args.read2)
            fastq_obj = untrimmed_fastq_obj.trim(args.files_prefix,threads=args.threads)
        elif args.read1 and not args.read2 and args.no_trim:
            # Unpaired + trimming
            fastq_obj = pp.fastq(args.read1,args.read2)
        elif args.read1 and not args.read2 and not args.no_trim:
            # Unpaired + trimming
            untrimmed_fastq_obj = pp.fastq(args.read1)
            fastq_obj = untrimmed_fastq_obj.trim(args.files_prefix,threads=args.threads)
        else:
            exit("\nPlease provide a bam file or a fastq file(s)...Exiting!\n")
        bam_obj = fastq_obj.map_to_ref(
            ref_file=conf["ref"], prefix=args.files_prefix,sample_name=args.prefix,
            aligner=args.mapper, platform=args.platform, threads=args.threads
        )
        bam_file = bam_obj.bam_file
    else:
        bam_file = args.bam

    if not args.missing_cov_threshold:
        args.missing_cov_threshold = args.min_depth
    else:
        sys.stderr.write("\nWARNING: The --missing_cov_threshold argument is deprecated and will be removed in future releases. This parameter can now be set with --min_depth.\n")


   
    args.conf = conf
    args.bam_file = bam_file
    args.run_delly = run_delly

    results.update(malp.malaria_bam_profiler(args))



    results["pipeline_software"].extend([
        {"Analysis":"Mapping","Program": args.mapper if not args.bam else "N/A"},
        {"Analysis":"Variant calling","Program":args.caller}
    ])
    results["resistance_db_version"] = json.load(open(conf["version"]))

    results = malp.reformat(results,conf)

    
    

    json.dump(results,open(json_output,"w"))
    if args.pdf:
        malp.write_pdf(results,conf,pdf_output)
    if args.txt:
        malp.write_text(results,conf,text_output,extra_columns,reporting_af=args.reporting_af)
    if args.csv:
        malp.write_text(results,conf,csv_output,extra_columns)

    ### Move files to respective directories ###
    result_files = {
        "%s.delly.bcf" % args.files_prefix: "%s/%s.delly.bcf" % (args.dir,args.prefix),
        "%s.targets.csq.vcf.gz" % args.files_prefix: "%s/%s.targets.csq.vcf.gz" % (args.dir,args.prefix),
        "%s.vcf.gz" % args.files_prefix: "%s/%s.vcf.gz" % (args.dir,args.prefix),
        "%s.bam" % args.files_prefix: "%s/%s.bam" % (args.dir,args.prefix),
        "%s.bam.bai" % args.files_prefix: "%s/%s.bam.bai" % (args.dir,args.prefix),
    }

    for file,target in result_files.items():
        if os.path.isfile(file):
            os.rename(file,target)

    pp.run_cmd(f"rm {args.files_prefix}*")

def create_species_db(args):
    pp.create_species_db(args)

def load_species_db(args):
    pp.load_species_db(args)

def create_resistance_db(args):
    if not os.path.isfile("genome.fasta") and os.path.isfile("genome.fasta.xz"):
        pp.run_cmd("xz -d genome.fasta.xz")
    if not os.path.isfile("genome.gff") and os.path.isfile("genome.gff.xz"):
        pp.run_cmd("xz -d genome.gff.xz")
    pp.create_db(args)
    if args.load:
        load_resistance_db(args)

def load_resistance_db(args):
    pp.load_resistance_db(args,{"geo_barcode":".barcode.bed"})


def main_speciate(args):
    if args.external_species_db:
        species_db = pp.get_species_db(args.software_name,args.external_species_db)
    else:
        species_db = pp.get_species_db(args.software_name,args.species_db)
        
    ### Create folders for results if they don't exist ###
    if pp.nofolder(args.dir):
        os.mkdir(args.dir)

    ### Setup prefix for files ###
    global files_prefix
    args.tmp_prefix = str(uuid4())
    files_prefix = args.dir+"/"+args.tmp_prefix

    json_output = args.dir+"/"+args.prefix+".results.json"
    text_output = args.dir+"/"+args.prefix+".results.txt"
    csv_output = args.dir+"/"+args.prefix+".results.csv"
    extra_columns = [x.lower() for x in args.add_columns.split(",")] if args.add_columns else []

    
    # pp.debug(species_db)
    
    species_prediction = malp.speciate(args)

    results = {"id":args.prefix,"species": species_prediction}
    results['software_version'] = malp.__version__
    results['pipeline_software'] = [{"Analysis":"Kmer counting","Program":"dsk"}]
    results['species_db_version'] = json.load(open(species_db["version"]))

    json.dump(results,open(json_output,"w"))
    if args.txt:
        malp.write_text(results,species_db,text_output,sep="\t")
    if args.csv:
        malp.write_text(results,species_db,csv_output,sep=",")

    pp.successlog("Profiling complete!")


def main_collate(args):
    malp.collate(args)


def main_update_db(args):
    if os.path.isdir('malaria-db'):
        os.chdir('malaria-db')
        pp.run_cmd('git pull')
        os.chdir('db/')
    else:
        pp.run_cmd('git clone https://github.com/jodyphelan/malaria-db.git')
        os.chdir('malaria-db/db/')
    dirs = [d for d in os.listdir() if os.path.isdir(d)]
    pp.infolog('\nCreating species DB\n')
    pp.run_cmd('malaria-profiler create_species_db -p plasmodium --kmers malaria.kmers.txt --load')
    for d in dirs:
        os.chdir(d)
        pp.debug(d)
        variables = json.load(open('variables.json'))
        if "enabled" in variables and variables["enabled"]==False: 
            os.chdir('../')
            continue
        for species in variables['species']:
            pp.infolog(f'\nCreating DB for {species}')
            pp.run_cmd(f'malaria-profiler create_resistance_db --prefix {species.replace(" ","_")} --csv {d}.csv --load')
        os.chdir('../')



#### Argument Parsing ####

parser = argparse.ArgumentParser(description='NTM-Profiler pipeline',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('--version', action='version', version="NTM-Profiler version %s" % malp.__version__)
parser.add_argument('--dir','-d',default=".",help='Storage directory')
parser.add_argument('--no_cleanup',action="store_true",help="Don't remove temporary files on error")
subparsers = parser.add_subparsers(help="Task to perform")


###### Profile #######
parser_sub = subparsers.add_parser('profile', help='Run whole profiling pipeline', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
input=parser_sub.add_argument_group("Input options")
group = input.add_mutually_exclusive_group(required=True)
group.add_argument('--read1','-1',help='First read file')
input.add_argument('--read2','-2',help='Second read file')
group.add_argument('--bam','-a',help='BAM file. Make sure it has been generated using the H37Rv genome (GCA_000195955.2)')
input.add_argument('--platform','-m',choices=["illumina","nanopore"],default="illumina",help='NGS Platform used to generate data')
input.add_argument('--resistance_db',help='Mutation panel name')
input.add_argument('--external_resistance_db',type=str,help='Path to db files prefix (overrides "--db" parameter)')
input.add_argument('--species_db',default='plasmodium',help='Mutation panel name')
input.add_argument('--external_species_db',type=str,help='Path to db files prefix (overrides "--db" parameter)')
input.add_argument('--mitochondria_seq_name',help='Used when bam/cram file is specified to extract mitochondial reads for species classification')

output=parser_sub.add_argument_group("Output options")
output.add_argument('--prefix','-p',default="malprofiler",help='Sample prefix for all results generated')
# output.add_argument('--dir','-d',default=".",help='Storage directory')
output.add_argument('--csv',action="store_true",help="Add CSV output")
output.add_argument('--txt',action="store_true",help="Add text output")
output.add_argument('--pdf',action="store_true",help="Add PDF output. This requires pdflatex to be installed")
output.add_argument('--add_columns',default=None,type=str,help="Add additional columns found in the mutation database to the text and csv results")
output.add_argument('--add_mutation_metadata',action="store_true",help=argparse.SUPPRESS)
output.add_argument('--call_whole_genome',action="store_true",help="Call whole genome")

algorithm=parser_sub.add_argument_group("Algorithm options")
algorithm.add_argument('--mapper',default="bwa", choices=["bwa","minimap2","bowtie2","bwa-mem2"],help="Mapping tool to use. If you are using nanopore data it will default to minimap2",type=str)
algorithm.add_argument('--caller',default="freebayes", choices=["bcftools","gatk","freebayes"],help="Variant calling tool to use.",type=str)
algorithm.add_argument('--calling_params',type=str,help='Override default parameters for variant calling')
algorithm.add_argument('--coverage_tool',default="bedtools", choices=["mosdepth","bedtools"],help="Variant calling tool to use.",type=str)
algorithm.add_argument('--min_depth',default=10,type=int,help='Minimum depth required to call variant. Bases with depth below this cutoff will be marked as missing')
algorithm.add_argument('--af',default=0.1,type=float,help='Minimum allele frequency to call variants')
algorithm.add_argument('--reporting_af',default=0.1,type=float,help='Minimum allele frequency to use variants for prediction')
algorithm.add_argument('--coverage_fraction_threshold',default=0,type=int,help='Cutoff used to calculate fraction of region covered by <= this value')
algorithm.add_argument('--missing_cov_threshold',type=int,help='Cutoff used to positions/codons in genes which are missing (this argument has now been merged with --min_depth argument and will be deprecated in future releases)')
algorithm.add_argument('--no_trim',action="store_true",help="Don't trim files using trimmomatic")
algorithm.add_argument('--no_flagstat',action="store_true",help="Don't collect flagstats")
algorithm.add_argument('--no_clip',action="store_false",help="Don't clip reads")
algorithm.add_argument('--no_delly',action="store_true",help="Don't run delly")
algorithm.add_argument('--no_species',action="store_true",help=argparse.SUPPRESS)
algorithm.add_argument('--add_variant_annotations',action="store_true",help=argparse.SUPPRESS)
algorithm.add_argument('--threads','-t',default=1,help='Threads to use',type=int)

other=parser_sub.add_argument_group("Other options")
other.add_argument('--verbose','-v',default=0, choices=[0,1,2],help="Verbosity increases from 0 to 2",type=int)
other.add_argument('--version', action='version', version="Malria-Profiler version %s" % malp.__version__)
other.add_argument('--no_cleanup',action="store_true",help="Don't remove temporary files on error")
other.add_argument('--delly_vcf',help=argparse.SUPPRESS)
parser_sub.set_defaults(func=main_profile)


parser_sub = subparsers.add_parser('collate', help='Collate results form multiple samples together', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--outfile','-o',default="malprofiler.collate.txt",help='Sample prefix')
parser_sub.add_argument('--samples',help='File with samples (one per line)')
parser_sub.add_argument('--dir','-d',default=".",help='Storage directory')
parser_sub.add_argument('--suffix',default=".results.json",type=str,help='Input results files suffix')
parser_sub.add_argument('--format',default="txt",choices=["txt","csv"],type=str,help='Output file type')
parser_sub.add_argument('--version', action='version', version="Malaria-Profiler version %s" % malp.__version__)
parser_sub.set_defaults(func=main_collate)

parser_sub = subparsers.add_parser('speciate', help='Run speciation pipeline', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
input=parser_sub.add_argument_group("Input options")
group = input.add_mutually_exclusive_group(required=True)
group.add_argument('--read1','-1',help='First read file')
input.add_argument('--read2','-2',help='Second read file')
group.add_argument('--bam','-a',help='BAM file. Make sure it has been generated using the H37Rv genome (GCA_000195955.2)')
input.add_argument('--platform','-m',choices=["illumina","nanopore"],default="illumina",help='NGS Platform used to generate data')
input.add_argument('--species_db',default='plasmodium',help='Speciation database name')
input.add_argument('--external_species_db',type=str,help='Path to db files prefix (overrides "--db" parameter)')
input.add_argument('--mitochondria_seq_name',help='Used when bam/cram file is specified to extract mitochondial reads for species classification')

output=parser_sub.add_argument_group("Output options")
output.add_argument('--prefix','-p',default="malprofiler",help='File prefix for all results generated')
output.add_argument('--dir','-d',default=".",help='Storage directory')
output.add_argument('--csv',action="store_true",help="Add CSV output")
output.add_argument('--txt',action="store_true",help="Add text output")
output.add_argument('--add_columns',default=None,type=str,help=argparse.SUPPRESS)

algorithm=parser_sub.add_argument_group("Algorithm options")
algorithm.add_argument('--threads','-t',default=1,help='Threads to use',type=int)

other=parser_sub.add_argument_group("Other options")
other.add_argument('--verbose','-v',default=0, choices=[0,1,2],help="Verbosity increases from 0 to 2",type=int)
other.add_argument('--version', action='version', version="NTM-Profiler version %s" % malp.__version__)
# other.add_argument('--no_cleanup',action="store_true",help="Don't remove temporary files on error")
parser_sub.set_defaults(func=main_speciate)



# Update database #
parser_sub = subparsers.add_parser('update_db', help='Update all databases', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--version', action='version', version="NTM-Profiler version %s" % malp.__version__)
parser_sub.set_defaults(func=main_update_db)




# Create resistance DB #
parser_sub = subparsers.add_parser('create_resistance_db', help='Generate the files required to run resistance profiling with NTM-Profiler', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--prefix','-p',type=str,help='The name of the database (match species name for automated speciation+resistance detection)',required = True)
parser_sub.add_argument('--csv','-c',type=str,help='The CSV file containing mutations')
parser_sub.add_argument('--load',action="store_true",help='Load the library after creating it')
parser_sub.add_argument('--watchlist','-w',type=str,help='A csv file containing genes to profile but without any specific associated mutations')
parser_sub.add_argument('--match_ref',type=str,help='The prefix for all output files')
parser_sub.add_argument('--other_annotations',type=str,help='The prefix for all output files')
parser_sub.add_argument('--custom',action="store_true",help='Tells the script this is a custom database, this is used to alter the generation of the version file')
parser_sub.add_argument('--db-name',help='Overrides the name of the database in the version file')
parser_sub.add_argument('--db-commit',help='Overrides the commit string of the database in the version file')
parser_sub.add_argument('--db-author',help='Overrides the author of the database in the version file')
parser_sub.add_argument('--db-date',help='Overrides the date of the database in the version file')
parser_sub.add_argument('--include_original_mutation',action="store_true", help='Include the original mutation (before reformatting) as part of the variant annotaion')
parser_sub.add_argument('--version', action='version', version="NTM-Profiler version %s" % malp.__version__)
parser_sub.set_defaults(func=create_resistance_db)

parser_sub = subparsers.add_parser('load_resistance_db', help='Load the resistance database files', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--prefix','-p',type=str,help='The input CSV file containing the mutations',required = True)
parser_sub.add_argument('--version', action='version', version="NTM-Profiler version %s" % malp.__version__)
parser_sub.set_defaults(func=load_resistance_db)

parser_sub = subparsers.add_parser('create_species_db', help='Generate the files required to run speciation with NTM-Profiler', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--prefix','-p',type=str,help='The name of the database',required = True)
parser_sub.add_argument('--kmers',type=str,help='The file containing species specific kmers',required = True)
parser_sub.add_argument('--load',action="store_true",help='Load the library after creating it')
parser_sub.add_argument('--db-name',help='Overrides the name of the database in the version file')
parser_sub.add_argument('--db-commit',help='Overrides the commit string of the database in the version file')
parser_sub.add_argument('--db-author',help='Overrides the author of the database in the version file')
parser_sub.add_argument('--db-date',help='Overrides the date of the database in the version file')
parser_sub.add_argument('--version', action='version', version="NTM-Profiler version %s" % malp.__version__)
parser_sub.set_defaults(func=create_species_db)

parser_sub = subparsers.add_parser('load_species_db', help='Load the species database files', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser_sub.add_argument('--prefix','-p',type=str,help='The name of the database',required = True)
parser_sub.add_argument('--version', action='version', version="NTM-Profiler version %s" % malp.__version__)
parser_sub.set_defaults(func=load_species_db)



args = parser.parse_args()
if hasattr(args, 'func'):
    args.software_name = __softwarename__
    args.tmp_prefix = str(uuid4())
    args.files_prefix = args.dir+"/"+args.tmp_prefix
    args.func(args)
else:
    parser.print_help(sys.stderr)